version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: rental_property_mgmt
      POSTGRES_USER: rental_user
      POSTGRES_PASSWORD: rental_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rental_user -d rental_property_mgmt"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: rental_user
      DB_PASSWORD: rental_password
      DB_NAME: rental_property_mgmt
      DB_SSLMODE: disable
      ENV: production
      PORT: 8080
      JWT_SECRET: change-this-in-production
      JWT_EXPIRES_IN: 24h
      CORS_ORIGINS: http://localhost
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
