version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: rental_property_mgmt
      POSTGRES_USER: rental_user
      POSTGRES_PASSWORD: rental_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rental_user -d rental_property_mgmt"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: rental_user
      DB_PASSWORD: rental_password
      DB_NAME: rental_property_mgmt
      DB_SSLMODE: disable
      ENV: development
      PORT: 8080
      JWT_SECRET: dev-jwt-secret-key
      JWT_EXPIRES_IN: 24h
      CORS_ORIGINS: http://localhost:5173
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/vendor
    working_dir: /app
    command: ["go", "run", "cmd/server/main.go"]
    restart: unless-stopped

  frontend-dev:
    image: node:18-alpine
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    environment:
      - NODE_ENV=development
    depends_on:
      - backend-dev
    restart: unless-stopped

volumes:
  postgres_data:
